export const vehicles = [
    {
        Name: "bifta",
        DisplayName: "Bifta",
        Hash: 3945366167,
        SignedHash: 1089547375,
        HexHash: "0xEB298297",
        DlcName: "mpbeach",
        HandlingId: "BIFTA",
        LayoutId: "LAYOUT_LOW_DUNE",
        Manufacturer: "BF",
        ManufacturerDisplayName: "BF",
        Class: "OFF_ROAD",
        Type: "CAR",
        PlateType: "FRONT_AND_BACK_PLATES",
        DashboardType: null,
        WheelType: "OFFROAD",
        Flags: [
            "FLAG_AVERAGE_CAR",
            "FLAG_POOR_CAR",
            "FLAG_IS_OFFROAD_VEHICLE",
            "FLAG_PEDS_INSIDE_CAN_BE_SET_ON_FIRE_MP",
        ],
        Seats: 2,
        Price: 9464,
        MonetaryValue: 50000,
        HasConvertibleRoof: false,
        HasSirens: false,
        Weapons: [],
        ModKits: ["83_bifta_modkit"],
        DimensionsMin: {
            X: -0.901133657,
            Y: -1.95356917,
            Z: -0.543574035,
        },
        DimensionsMax: {
            X: 0.9011322,
            Y: 1.55852461,
            Z: 0.8312561,
        },
        BoundingCenter: {
            X: 0.0,
            Y: -0.092734,
            Z: 0.202604,
        },
        BoundingSphereRadius: 1.925178,
        Rewards: null,
        MaxBraking: 0.7,
        MaxBrakingMods: 0.8,
        MaxSpeed: 45.1953163,
        MaxTraction: 2.05,
        Acceleration: 0.26,
        Agility: 0.64,
        MaxKnots: 0.0,
        MoveResistance: 0.0,
    },
    // Weitere Fahrzeuge hier...
];