name = "raycast_marker"
description = "Eine Resource, die einen Marker um ein Ziel zeichnet, wenn es per Raycast angesehen wird."
author = "Dein Name"
version = "1.0.0"

client-files = [
    "includes/*",
    "client.js"
]

client-main = "client.js"
main = "index.js"
type = "js"